theme: jekyll-theme-minimal
title: Zk Ckickens Lottery
description: Zk Ckickens' open-source lottery web page! All players can check the lottery system we use and its results to ensure the lottery mechanism works fair!
