const weeks = [
  {                   // Weeek 1
    seed: 25940,
    pools: [
      { name: 'Pool 1', size: 3, prize: 100, winners: [] },
      { name: 'Pool 2', size: 5, prize: 150, winners: [] },
      { name: 'Pool 3', size: 10, prize: 200, winners: [] },
    ],
    players: [
      { address: 'Address 1', eggs: 50, tickets: 50 },
      { address: 'Address 2', eggs: 5, tickets: 3 },
      { address: 'Address 3', eggs: 5, tickets: 2 },
      { address: 'Address 4', eggs: 5, tickets: 2 },
      { address: 'Address 5', eggs: 5, tickets: 2 },
      { address: 'Address 6', eggs: 5, tickets: 2 },
      { address: 'Address 7', eggs: 5, tickets: 2 },
      { address: 'Address 8', eggs: 5, tickets: 2 },
      { address: 'Address 9', eggs: 5, tickets: 2 },
      { address: 'Address 10', eggs: 5, tickets: 2 },
      { address: 'Address 11', eggs: 5, tickets: 2 },
      { address: 'Address 12', eggs: 5, tickets: 2 },
      { address: 'Address 13', eggs: 5, tickets: 2 },
      { address: 'Address 14', eggs: 5, tickets: 2 },
      { address: 'Address 15', eggs: 5, tickets: 2 },
      { address: 'Address 16', eggs: 5, tickets: 2 },
      { address: 'Address 17', eggs: 5, tickets: 2 },
      { address: 'Address 18', eggs: 5, tickets: 2 },
      { address: 'Address 19', eggs: 5, tickets: 2 },
      { address: 'Address 20', eggs: 5, tickets: 2 },
      { address: 'Address 21', eggs: 5, tickets: 2 },
      { address: 'Address 22', eggs: 5, tickets: 2 },
      { address: 'Address 23', eggs: 5, tickets: 2 },
      { address: 'Address 24', eggs: 5, tickets: 2 },
      { address: 'Address 25', eggs: 5, tickets: 2 },
      { address: 'Address 26', eggs: 5, tickets: 2 },
      { address: 'Address 27', eggs: 5, tickets: 2 },
      { address: 'Address 28', eggs: 5, tickets: 2 },
      { address: 'Address 29', eggs: 5, tickets: 2 },
      { address: 'Address 30', eggs: 5, tickets: 2 },
    ],
  },
  {                   // Weeek 2
    seed: 32500,
    pools: [
      { name: 'Pool 1', size: 5, prize: 200, winners: [] },
      { name: 'Pool 2', size: 10, prize: 300, winners: [] },
    ],
    players: [
      { address: 'Address 1', eggs: 100, tickets: 50 },
      { address: 'Address 2', eggs: 5, tickets: 3 },
      { address: 'Address 3', eggs: 5, tickets: 2 },
      { address: 'Address 4', eggs: 5, tickets: 2 },
      { address: 'Address 5', eggs: 5, tickets: 2 },
      { address: 'Address 6', eggs: 5, tickets: 2 },
      { address: 'Address 7', eggs: 5, tickets: 2 },
      { address: 'Address 8', eggs: 5, tickets: 2 },
      { address: 'Address 9', eggs: 5, tickets: 2 },
      { address: 'Address 10', eggs: 5, tickets: 2 },
      { address: 'Address 11', eggs: 5, tickets: 2 },
      { address: 'Address 12', eggs: 5, tickets: 2 },
      { address: 'Address 13', eggs: 5, tickets: 2 },
      { address: 'Address 14', eggs: 5, tickets: 2 },
      { address: 'Address 15', eggs: 5, tickets: 2 },
      { address: 'Address 16', eggs: 5, tickets: 2 },
      { address: 'Address 17', eggs: 5, tickets: 2 },
      { address: 'Address 18', eggs: 5, tickets: 2 },
      { address: 'Address 19', eggs: 5, tickets: 2 },
      { address: 'Address 20', eggs: 5, tickets: 2 },
      { address: 'Address 21', eggs: 5, tickets: 2 },
      { address: 'Address 22', eggs: 5, tickets: 2 },
      { address: 'Address 23', eggs: 5, tickets: 2 },
      { address: 'Address 24', eggs: 5, tickets: 2 },
      { address: 'Address 25', eggs: 5, tickets: 2 },
      { address: 'Address 26', eggs: 5, tickets: 2 },
      { address: 'Address 27', eggs: 5, tickets: 2 },
      { address: 'Address 28', eggs: 5, tickets: 2 },
      { address: 'Address 29', eggs: 5, tickets: 2 },
      { address: 'Address 30', eggs: 5, tickets: 2 },
    ],
  },
]